### ISSUE TITLE
Update vulnerable `BouncyCastle.Cryptography` dependency

### ISSUE THREAD

**Issue by enricobenedos** [questdb/net-questdb-client#30]
You are currently referencing `BouncyCastle.Cryptography 2.2.1` that have been signed as vulnerable. 
It should be a good idea to update it. 

Vulnerabilities:
- https://github.com/advisories/GHSA-8xfc-gm6g-vgpv
- https://github.com/advisories/GHSA-v435-xc8x-wvr9
- https://github.com/advisories/GHSA-m44j-cfrm-g8qc

**Comment by nandor23** [comment]
This is a real issue, since your pull request a newer version of `BouncyCastle.Cryptography` came out. Vulnerabilities are explicitly listed `nuget.org` as well: https://www.nuget.org/packages/BouncyCastle.Cryptography/2.1.1

**Comment by ideoma** [comment]
fixed in #34
